#!/usr/bin/env python3
"""
scanner.py — SN Security Migrator
Copyright (c) 2026 Vladimir Kapustin. License: AGPL-3.0
"""
import json, os, re
from dataclasses import dataclass, asdict, field
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

import requests

DEFAULT_INSTANCE = "https://dev362840.service-now.com"
DEFAULT_USER = "admin"
DEFAULT_PASS = os.environ.get("SN_PASSWORD", "7%%gXJzImsW7")

FAILURE_TYPES = {
    "password": re.compile(r'password|passwd|credential|pwd', re.I),
    "encryption": re.compile(r'encrypt|key|certificate|ssl|tls', re.I),
    "acl": re.compile(r'acl|access.*control|security.*rule', re.I),
    "snc_identity": re.compile(r'snc.*identity|instance.*id|sys_id.*migration', re.I),
    "mid_server": re.compile(r'mid.*server|ecc.*queue|agent', re.I),
}

@dataclass
class FailedJob:
    sys_id: str
    name: str
    state: str
    error_message: str
    failure_type: str
    fix_script: str

@dataclass
class SecurityReport:
    instance: str
    timestamp: str
    total_jobs: int
    failed_jobs: int
    jobs: List[FailedJob]

class SecurityMigrator:
    def __init__(self, instance: str = DEFAULT_INSTANCE, user: str = DEFAULT_USER, password: str = DEFAULT_PASS):
        self.instance = instance.rstrip("/")
        self.auth = (user, password)
        self.headers = {"Accept": "application/json", "Content-Type": "application/json"}

    def _get(self, endpoint: str, params: Optional[dict] = None) -> List[dict]:
        url = f"{self.instance}{endpoint}"
        r = requests.get(url, auth=self.auth, headers=self.headers, params=params or {}, timeout=30)
        if r.status_code != 200:
            raise RuntimeError(f"GET {url} => {r.status_code}: {r.text[:200]}")
        return r.json().get("result", [])

    def list_schedule_entries(self, limit: int = 500) -> List[dict]:
        return self._get("/api/now/table/sys_schedule_entry", {
            "sysparm_limit": limit,
            "sysparm_fields": "sys_id,name,state,error_message,sys_created_on",
            "sysparm_query": "nameLIKEsecurity^state=failure",
        })

    def classify_failure(self, error_message: str) -> str:
        for ftype, pattern in FAILURE_TYPES.items():
            if pattern.search(error_message):
                return ftype
        return "unknown"

    def generate_fix_script(self, ftype: str, job_name: str) -> str:
        base = f"// Fix script for {job_name} \n// Generated by SN Security Migrator \n"
        scripts = {
            "password": base + "gs.info('Migrating password records...');\n// Move to Password Reset v2 or update password policy",
            "encryption": base + "gs.info('Syncing encryption keys...');\n// Run Encryption Key Management module",
            "acl": base + "gs.info('Migrating ACLs...');\n// Review ACL inheritance for Zurich",
            "snc_identity": base + "gs.info('Fixing SNC Identity...');\n// Regenerate instance identity",
            "mid_server": base + "gs.info('Checking MID server...');\n// Validate ECC queue",
            "unknown": base + "gs.info('Manual review required');\n",
        }
        return scripts.get(ftype, scripts["unknown"])

    def run(self, limit: int = 500) -> SecurityReport:
        entries = self.list_schedule_entries(limit)
        jobs = []
        for e in entries:
            err = e.get("error_message", "")
            ftype = self.classify_failure(err)
            jobs.append(FailedJob(
                sys_id=e.get("sys_id", ""),
                name=e.get("name", ""),
                state=e.get("state", ""),
                error_message=err,
                failure_type=ftype,
                fix_script=self.generate_fix_script(ftype, e.get("name", "")),
            ))
        return SecurityReport(
            instance=self.instance,
            timestamp=datetime.now(timezone.utc).isoformat(),
            total_jobs=len(jobs),
            failed_jobs=len(jobs),
            jobs=jobs,
        )

    def save_report(self, report: SecurityReport, out_dir: str = "reports") -> Path:
        Path(out_dir).mkdir(parents=True, exist_ok=True)
        ts = report.timestamp[:10]
        host = report.instance.split("//")[-1]
        js = Path(out_dir) / f"security_migrator_{ts}_{host}.json"
        js.write_text(json.dumps(asdict(report), ensure_ascii=False, indent=2))
        html = Path(out_dir) / f"security_migrator_{ts}_{host}.html"
        html.write_text(self._render_html(report))
        return html

    @staticmethod
    def _render_html(report: SecurityReport) -> str:
        rows = ""
        for j in report.jobs:
            rows += f"""
<tr><td>{j.sys_id}</td><td>{j.name}</td><td>{j.state}</td><td>{j.failure_type}</td><td><pre>{j.error_message}</pre></td><td><pre>{j.fix_script}</pre></td></tr>\n"""
        return f"""
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>SN Security Migrator Report</title>
<style>body{{font-family:DejaVu Sans;margin:40px}}h1{{color:#0F1D35}}.summary{{font-size:1.2em;margin-bottom:20px}}table{{border-collapse:collapse;width:100%}}th,td{{border:1px solid #ddd;padding:8px;padding-top:0.5em}}th{{background:#0F1D35;color:white}}pre{{white-space:pre-wrap;font-size:0.9em;background:#f6f6f6;padding:8px;border-radius:4px}}</style>
</head><body>
<h1>ServiceNow Security Migration Job Cleaner Report</h1>
<div class="summary"><b>Instance:</b> {report.instance} | <b>Failed Jobs:</b> {report.failed_jobs}</div>
<table><tr><th>ID</th><th>Name</th><th>State</th><th>Type</th><th>Error</th><th>Fix Script</th></tr>
{rows}</table>
<p style="font-size:0.8em;color:#555">Copyright (c) 2026 Vladimir Kapustin. License: AGPL-3.0</p>
</body></html>
"""

if __name__ == "__main__":
    m = SecurityMigrator()
    report = m.run()
    path = m.save_report(report)
    print(f"Failed jobs: {report.failed_jobs} | Report: {path}")
    print(json.dumps(asdict(report), ensure_ascii=False, indent=2))
