// DemoSeed — DemoSeedHelper Script Include
// Copyright (C) 2026 Vladimir Kapustin
// SPDX-License-Identifier: AGPL-3.0
//
// Support services: Refresh Scheduler, Snapshot Manager, AI Description Generator, Field Mapper
// Consolidated from 4 design SIs into 1 (max 2 SI constraint)
// @class DemoSeedHelper @namespace x_demoseed

var DemoSeedHelper = Class.create();
DemoSeedHelper.prototype = {
    initialize: function() {
        this.configTable = 'x_demoseed_config';
        this.auditTable = 'x_demoseed_audit';
    },

    // ─── REFRESH SCHEDULER ────────────────────────────────────────────

    /**
     * Daily refresh: add new records and simulate aging.
     * Called by scheduled job. Reads active profiles and generates incremental data.
     * @returns {Object} { profiles_processed, total_new_records, errors }
     */
    refreshDaily: function() {
        var result = { profiles_processed: 0, total_new_records: 0, errors: [] };

        var profileGr = new GlideRecord(this.configTable);
        profileGr.addQuery('config_type', 'profile');
        profileGr.addQuery('active', 'true');
        profileGr.query();

        while (profileGr.next()) {
            // Check if this profile has an auto-stop date
            var endDateStr = profileGr.getValue('description') || '';
            if (endDateStr && endDateStr.indexOf('stop:') === 0) {
                var stopDate = endDateStr.substring(5);
                var now = new GlideDateTime();
                if (now.getValue() > stopDate) {
                    gs.info('[DemoSeed] Profile ' + profileGr.getValue('name') + ' auto-stopped');
                    continue;
                }
            }

            try {
                var core = new DemoSeedCore();
                var dailyVolume = Math.floor(parseInt(profileGr.getValue('volume'), 10) / 30) || 16;
                var genResult = core.generate(profileGr.getUniqueValue(), dailyVolume, 1);
                result.profiles_processed++;
                result.total_new_records += genResult.total_records || 0;
                if (genResult.errors && genResult.errors.length > 0) {
                    result.errors = result.errors.concat(genResult.errors);
                }
            } catch (e) {
                result.errors.push('Profile ' + profileGr.getValue('name') + ': ' + e.message);
            }
        }

        // Simulate aging: close old incidents
        try {
            this._simulateAging();
        } catch (e) {
            result.errors.push('Aging simulation: ' + e.message);
        }

        return result;
    },

    /**
     * Simulate aging: close old open incidents that were generated by DemoSeed.
     */
    _simulateAging: function() {
        var auditGr = new GlideRecord(this.auditTable);
        auditGr.addQuery('is_batch_header', 'false');
        auditGr.addQuery('target_table', 'incident');
        auditGr.addQuery('wiped', 'false');
        auditGr.addQuery('sys_created_on', '<=', gs.daysAgoStart(30));
        auditGr.setLimit(50);
        auditGr.query();

        while (auditGr.next()) {
            var incSysId = auditGr.getValue('record_sys_id');
            var incGr = new GlideRecord('incident');
            if (incGr.get(incSysId)) {
                var state = incGr.getValue('state');
                if (state !== '7' && state !== '6') {
                    incGr.setValue('state', '7');
                    incGr.setValue('close_code', 'closed_by_caller');
                    incGr.setValue('closed_at', new GlideDateTime().getValue());
                    try {
                        incGr.update();
                    } catch (e) {
                        gs.debug('[DemoSeed] Aging update failed: ' + e.message);
                    }
                }
            }
        }
    },

    /**
     * Check if a profile should stop refreshing.
     * @param {string} profileId
     * @returns {boolean}
     */
    shouldStop: function(profileId) {
        var profileGr = new GlideRecord(this.configTable);
        if (!profileGr.get(profileId)) return true;

        var desc = profileGr.getValue('description') || '';
        if (desc.indexOf('stop:') === 0) {
            var stopDate = desc.substring(5);
            var now = new GlideDateTime();
            return now.getValue() > stopDate;
        }
        return false;
    },

    // ─── SNAPSHOT MANAGER ─────────────────────────────────────────────

    /**
     * Save current DemoSeed data state as a named snapshot.
     * @param {string} name - snapshot name
     * @param {string} description - optional description
     * @returns {string} sys_id of the created snapshot
     */
    saveSnapshot: function(name, description) {
        var snapshotData = this._collectSnapshotData();

        var snapGr = new GlideRecord(this.configTable);
        snapGr.initialize();
        snapGr.setValue('name', name);
        snapGr.setValue('config_type', 'snapshot');
        snapGr.setValue('description', description || '');
        snapGr.setValue('snapshot_data', JSON.stringify(snapshotData));
        snapGr.setValue('record_count', snapshotData.total_records);
        snapGr.setValue('active', 'true');

        try {
            return snapGr.insert();
        } catch (e) {
            gs.error('[DemoSeed] Snapshot insert failed: ' + e.message);
            return '';
        }
    },

    /**
     * Restore a named snapshot by regenerating the data.
     * @param {string} snapshotId - sys_id of the snapshot config record
     * @returns {Object} { restored_count, errors }
     */
    restoreSnapshot: function(snapshotId) {
        var snapGr = new GlideRecord(this.configTable);
        if (!snapGr.get(snapshotId)) {
            return { error: 'Snapshot not found: ' + snapshotId };
        }

        var snapshotDataJson = snapGr.getValue('snapshot_data') || '{}';
        var snapshotData;
        try {
            snapshotData = JSON.parse(snapshotDataJson);
        } catch (e) {
            return { error: 'Invalid snapshot data: ' + e.message };
        }

        var core = new DemoSeedCore();
        var profileId = snapshotData.profile_id;
        var volume = snapshotData.volume || 500;
        var dateRange = snapshotData.date_range_days || 90;

        return core.generate(profileId, volume, dateRange);
    },

    /**
     * Export snapshot as XML string.
     * @param {string} snapshotId
     * @returns {string} XML string
     */
    exportXML: function(snapshotId) {
        var snapGr = new GlideRecord(this.configTable);
        if (!snapGr.get(snapshotId)) {
            return '<error>Snapshot not found</error>';
        }

        var xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
        xml += '<DemoSeedSnapshot>\n';
        xml += '  <name>' + this._xmlEscape(snapGr.getValue('name') || '') + '</name>\n';
        xml += '  <description>' + this._xmlEscape(snapGr.getValue('description') || '') + '</description>\n';
        xml += '  <record_count>' + (snapGr.getValue('record_count') || '0') + '</record_count>\n';
        xml += '  <created_on>' + this._xmlEscape(snapGr.getValue('sys_created_on') || '') + '</created_on>\n';
        xml += '  <data><![CDATA[' + (snapGr.getValue('snapshot_data') || '{}') + ']]></data>\n';
        xml += '</DemoSeedSnapshot>';

        return xml;
    },

    _collectSnapshotData: function() {
        var data = { total_records: 0, batches: [], profile_id: '', volume: 0, date_range_days: 0 };

        var batchGr = new GlideRecord(this.auditTable);
        batchGr.addQuery('is_batch_header', 'true');
        batchGr.addQuery('status', 'IN', 'complete,running');
        batchGr.orderByDesc('sys_created_on');
        batchGr.setLimit(10);
        batchGr.query();

        while (batchGr.next()) {
            data.batches.push({
                batch_id: batchGr.getValue('batch_id'),
                total_records: parseInt(batchGr.getValue('total_records'), 10) || 0,
                tables_processed: batchGr.getValue('tables_processed') || '[]',
                started_on: batchGr.getValue('started_on') || '',
                completed_on: batchGr.getValue('completed_on') || ''
            });
            data.total_records += parseInt(batchGr.getValue('total_records'), 10) || 0;
            if (!data.profile_id) {
                data.profile_id = batchGr.getValue('profile_id') || '';
            }
        }

        return data;
    },

    _xmlEscape: function(str) {
        if (!str) return '';
        return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
    },

    // ─── AI DESCRIPTION GENERATOR ─────────────────────────────────────

    /**
     * Generate realistic descriptions using GenAI Controller (BYOK).
     * Falls back to template-based generation if AI is disabled or unavailable.
     * @param {string} tableName - target table
     * @param {number} count - number of descriptions needed
     * @returns {Array} Array of description strings
     */
    generateDescriptions: function(tableName, count) {
        var aiEnabled = gs.getProperty('x_demoseed.ai_enabled', 'false') === 'true';

        if (!aiEnabled) {
            return this._templateDescriptions(tableName, count);
        }

        try {
            var prompt = this._getAIPrompt('description_generator');
            if (!prompt) {
                return this._templateDescriptions(tableName, count);
            }

            var promptText = prompt.replace('{table}', tableName).replace('{count}', String(count));

            // Call GenAI Controller
            var genAI = new sn_generative_ai.GlideGenerativeAI();
            var response = genAI.generate(promptText, { max_tokens: 2000 });

            if (response && response.text) {
                var lines = response.text.split('\n').filter(function(l) { return l.trim().length > 0; });
                return lines.slice(0, count);
            }
        } catch (e) {
            gs.warn('[DemoSeed] AI description generation failed: ' + e.message);
        }

        return this._templateDescriptions(tableName, count);
    },

    /**
     * Generate a demo narrative/talking points for a dashboard.
     * @param {Object} dashboardData - dashboard metrics summary
     * @returns {string} Narrative text
     */
    generateDemoNarrative: function(dashboardData) {
        var aiEnabled = gs.getProperty('x_demoseed.ai_enabled', 'false') === 'true';

        if (!aiEnabled) {
            return this._templateNarrative(dashboardData);
        }

        try {
            var prompt = this._getAIPrompt('demo_narrative');
            if (!prompt) {
                return this._templateNarrative(dashboardData);
            }

            var promptText = prompt.replace('{data}', JSON.stringify(dashboardData));

            var genAI = new sn_generative_ai.GlideGenerativeAI();
            var response = genAI.generate(promptText, { max_tokens: 1000 });

            if (response && response.text) {
                return response.text;
            }
        } catch (e) {
            gs.warn('[DemoSeed] AI narrative generation failed: ' + e.message);
        }

        return this._templateNarrative(dashboardData);
    },

    /**
     * Validate generated data quality using AI.
     * @param {Array} records - sample records to validate
     * @returns {Object} { issues: Array, score: number }
     */
    validateDataQuality: function(records) {
        var aiEnabled = gs.getProperty('x_demoseed.ai_enabled', 'false') === 'true';

        if (!aiEnabled) {
            return this._basicQualityCheck(records);
        }

        try {
            var prompt = this._getAIPrompt('quality_validator');
            if (!prompt) {
                return this._basicQualityCheck(records);
            }

            var promptText = prompt.replace('{records}', JSON.stringify(records.slice(0, 20)));

            var genAI = new sn_generative_ai.GlideGenerativeAI();
            var response = genAI.generate(promptText, { max_tokens: 500 });

            if (response && response.text) {
                try {
                    return JSON.parse(response.text);
                } catch (e) {
                    return { issues: [response.text], score: 50 };
                }
            }
        } catch (e) {
            gs.warn('[DemoSeed] AI quality validation failed: ' + e.message);
        }

        return this._basicQualityCheck(records);
    },

    _getAIPrompt: function(promptName) {
        var promptGr = new GlideRecord(this.configTable);
        promptGr.addQuery('config_type', 'ai_prompt');
        promptGr.addQuery('name', promptName);
        promptGr.addQuery('active', 'true');
        promptGr.query();
        if (promptGr.next()) {
            return promptGr.getValue('prompt_text') || '';
        }
        return '';
    },

    _templateDescriptions: function(tableName, count) {
        var templates = {
            'incident': [
                'User reported service degradation during peak hours. Initial diagnostics indicate resource contention on application server.',
                'Monitoring alert triggered for high latency on payment gateway. Affected transactions queued for reprocessing.',
                'Customer reported inability to access portal after password reset. Session token validation failure suspected.',
                'Automated health check detected memory leak in reporting service. Service restarted, root cause under investigation.',
                'Help desk ticket escalated from L1 — user unable to authenticate via SSO after domain migration.'
            ],
            'change_request': [
                'Routine security patch deployment for web application firewall. Tested in staging, no regressions detected.',
                'Database index rebuild to address query performance degradation. Estimated 15% improvement in report generation.',
                'SSL certificate renewal for *.company.com wildcard. New cert issued by DigiCert, valid until 2027.',
                'Load balancer configuration update to add new application server to pool. Zero-downtime deployment.'
            ],
            'sc_req_item': [
                'Standard new hire equipment package: laptop, monitor, keyboard, headset. Delivery to Building A, Floor 3.',
                'Software license renewal for engineering team — JetBrains All Products Pack, 25 seats.',
                'Access card replacement for employee transferring from Building B to Building A.',
                'Conference room technology upgrade — new video conferencing equipment for Room 401.'
            ]
        };

        var pool = templates[tableName] || [
            'Auto-generated record for demo purposes — DemoSeed batch.',
            'Synthetic data record created by DemoSeed for Performance Analytics population.',
            'Demo data record — realistic scenario simulation for dashboard testing.'
        ];

        var result = [];
        for (var i = 0; i < count; i++) {
            result.push(pool[Math.floor(Math.random() * pool.length)]);
        }
        return result;
    },

    _templateNarrative: function(dashboardData) {
        var narrative = 'Demo Data Summary\n';
        narrative += '==================\n\n';
        narrative += 'Your dashboards now show ' + (dashboardData.total_incidents || 0) + ' incidents ';
        narrative += 'over ' + (dashboardData.date_range_days || 90) + ' days.\n\n';
        narrative += 'Recommended talking points:\n';
        narrative += '1. MTTR trend over the last 8 weeks\n';
        narrative += '2. Backlog by assignment group\n';
        narrative += '3. SLA compliance heatmap\n';
        narrative += '4. Incident volume by category\n';
        narrative += '5. Change success rate over time\n';
        return narrative;
    },

    _basicQualityCheck: function(records) {
        var issues = [];
        var timestamps = [];
        var priorities = {};

        for (var i = 0; i < records.length; i++) {
            var rec = records[i];
            if (rec.opened_at) timestamps.push(rec.opened_at);
            if (rec.priority) {
                priorities[rec.priority] = (priorities[rec.priority] || 0) + 1;
            }
        }

        // Check for all-same-hour clustering
        if (timestamps.length > 5) {
            var hours = {};
            for (var h = 0; h < timestamps.length; h++) {
                var hour = timestamps[h].substring(11, 13);
                hours[hour] = (hours[hour] || 0) + 1;
            }
            var maxHour = 0;
            var hourKeys = Object.keys(hours);
            for (var k = 0; k < hourKeys.length; k++) {
                if (hours[hourKeys[k]] > maxHour) maxHour = hours[hourKeys[k]];
            }
            if (maxHour > timestamps.length * 0.5) {
                issues.push('Time clustering detected: ' + maxHour + ' of ' + timestamps.length + ' records in same hour');
            }
        }

        // Check priority distribution
        var total = records.length;
        if (total > 10) {
            var p1Pct = ((priorities['1'] || 0) / total) * 100;
            if (p1Pct > 20) {
                issues.push('P1 ratio too high: ' + p1Pct.toFixed(1) + '% (expected ~5%)');
            }
        }

        return { issues: issues, score: issues.length === 0 ? 100 : Math.max(0, 100 - issues.length * 15) };
    },

    // ─── FIELD MAPPER ─────────────────────────────────────────────────

    /**
     * Suggest field-to-generation-type mappings for a custom table.
     * Inspects table schema and returns suggested mappings.
     * @param {string} tableName
     * @returns {Array} Array of { field_name, suggested_type, reason }
     */
    suggestMappings: function(tableName) {
        var suggestions = [];
        var dictGr = new GlideRecord('sys_dictionary');
        dictGr.addQuery('name', tableName);
        dictGr.addQuery('active', 'true');
        dictGr.query();

        while (dictGr.next()) {
            var fieldName = dictGr.getValue('element');
            var internalType = dictGr.getValue('internal_type');
            var choice = parseInt(dictGr.getValue('choice'), 10) || 0;
            var reference = dictGr.getValue('reference') || '';

            // Skip system fields
            if (fieldName.indexOf('sys_') === 0) continue;

            var suggestedType = 'string';
            var reason = 'Default string type';

            if (choice > 0) {
                suggestedType = 'choice';
                reason = 'Has ' + choice + ' choice values';
            } else if (reference) {
                suggestedType = 'reference';
                reason = 'References ' + reference;
            } else if (internalType === 'glide_date_time' || internalType === 'glide_date') {
                suggestedType = 'date';
                reason = 'Date/time field';
            } else if (internalType === 'integer' || internalType === 'decimal' || internalType === 'float') {
                suggestedType = 'numeric';
                reason = 'Numeric field';
            } else if (internalType === 'boolean') {
                suggestedType = 'boolean';
                reason = 'Boolean field';
            }

            suggestions.push({
                field_name: fieldName,
                suggested_type: suggestedType,
                reason: reason
            });
        }

        return suggestions;
    },

    /**
     * Apply field mappings for a table — creates config records.
     * @param {string} tableName
     * @param {Array} mappings - [{ field_name, generation_type, weight_json }]
     * @returns {number} Number of mappings created
     */
    applyMapping: function(tableName, mappings) {
        var created = 0;

        for (var m = 0; m < mappings.length; m++) {
            var mapping = mappings[m];
            try {
                var mapGr = new GlideRecord(this.configTable);
                mapGr.initialize();
                mapGr.setValue('name', tableName + '_' + mapping.field_name);
                mapGr.setValue('config_type', 'field_map');
                mapGr.setValue('table_name', tableName);
                mapGr.setValue('field_name', mapping.field_name);
                mapGr.setValue('generation_type', mapping.generation_type);
                mapGr.setValue('weight_json', mapping.weight_json || '');
                mapGr.setValue('active', 'true');
                mapGr.insert();
                created++;
            } catch (e) {
                gs.warn('[DemoSeed] Failed to create field mapping: ' + e.message);
            }
        }

        return created;
    },

    /**
     * Generate a single field value for a custom table.
     * @param {string} tableName
     * @param {string} fieldName
     * @param {string} type - generation type
     * @returns {string} Generated value
     */
    generateField: function(tableName, fieldName, type) {
        var core = new DemoSeedCore();
        var startDate = new GlideDateTime();
        startDate.addSeconds(-90 * 86400);
        var endDate = new GlideDateTime();

        var mapping = {
            table_name: tableName,
            field_name: fieldName,
            generation_type: type,
            weight_json: ''
        };

        return core._generateFieldValue(mapping, startDate, endDate);
    },

    type: 'DemoSeedHelper'
};
